# -*- coding: utf-8 -*-
import sys, \
    os
if hasattr(sys, 'frozen'):
    os.environ['PATH'] = sys._MEIPASS + ";" + os.environ['PATH']

from PyQt5.QtWidgets import QWidget, QLabel, QHBoxLayout, QGroupBox, QGridLayout, QLineEdit, QPushButton, QTextBrowser, QCheckBox, QComboBox, QVBoxLayout,QFrame
from PyQt5.QtGui import QFont, QPixmap, QPalette, QColor, QCursor, QBrush, QIcon
from PyQt5.QtCore import QRect, Qt, QMetaObject, QCoreApplication, QTimer

from linkSHUPath import shuPath
from timg_png import img as timg
import base64

linkpath = shuPath()

sss = os.path.exists(linkpath + r'\timg.png')
if not sss:
    tmp = open(linkpath + r'\timg.png', 'wb')
    tmp.write(base64.b64decode(timg))
    tmp.close()
else:
    pass


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(771, 501)
        font = QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QFrame(self.centralwidget)

        self.frame.setStyleSheet("background-color: rgb(52, 59, 72);\n"
                                 "border-radius:10;\n"
                                 "")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setGeometry(QRect(1, 0, 240, 500))
        self.frame.setObjectName("frame")

        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QRect(240, 70, 350, 160))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")

        self.gridLayoutWidget = QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QRect(75, 10, 213, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.input_user = QLineEdit(self.gridLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.input_user.setFont(font)
        self.input_user.setText("")
        self.input_user.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.input_user.setObjectName("input_user")
        self.gridLayout.addWidget(self.input_user, 0, 1, 1, 1)
        self.user = QLabel(self.gridLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.user.setFont(font)
        self.user.setAlignment(Qt.AlignCenter)
        self.user.setObjectName("user")
        self.gridLayout.addWidget(self.user, 0, 0, 1, 1)
        self.input_passwd = QLineEdit(self.gridLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.input_passwd.setFont(font)
        self.input_passwd.setFocusPolicy(Qt.StrongFocus)
        self.input_passwd.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.input_passwd.setText("")
        self.input_passwd.setEchoMode(QLineEdit.Password)
        self.input_passwd.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.input_passwd.setObjectName("input_passwd")
        self.gridLayout.addWidget(self.input_passwd, 1, 1, 1, 1)
        self.passwd = QLabel(self.gridLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.passwd.setFont(font)
        self.passwd.setAlignment(Qt.AlignCenter)
        self.passwd.setObjectName("passwd")
        self.gridLayout.addWidget(self.passwd, 1, 0, 1, 1)
        self.horizontalLayoutWidget = QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QRect(100, 102, 211, 26))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_7 = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.passwdCB = QCheckBox(self.horizontalLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.passwdCB.setFont(font)
        self.passwdCB.setObjectName("passwdCB")
        self.horizontalLayout_7.addWidget(self.passwdCB)
        self.auto_login = QCheckBox(self.horizontalLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.auto_login.setFont(font)
        self.auto_login.setObjectName("auto_login")
        self.horizontalLayout_7.addWidget(self.auto_login)

        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QRect(240, 230, 350, 200))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QRect(50, 10, 260, 160))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.status_lable = QLabel(self.verticalLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.status_lable.setFont(font)
        self.status_lable.setAlignment(Qt.AlignCenter)
        self.status_lable.setObjectName("status_lable")
        self.verticalLayout.addWidget(self.status_lable)
        self.status = QTextBrowser(self.verticalLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.status.setFont(font)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)

        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "border-radius:10;\n"
                                 "")
        self.groupBox_3.setGeometry(QRect(249, 430, 520, 70))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.updateLabel = QLabel(self.groupBox_3)
        self.updateLabel.setGeometry(QRect(140, 20, 260, 30))
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.updateLabel.setFont(font)
        self.updateLabel.setCursor(QCursor(Qt.PointingHandCursor))
        self.updateLabel.setToolTip("")
        self.updateLabel.setAlignment(Qt.AlignCenter)
        self.updateLabel.setObjectName("updateLabel")
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QRect(240, 0, 560, 70))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")

        self.logo = QLabel(self.groupBox_4)
        self.logo.setGeometry(QRect(30, 10, 130, 50))
        self.logo.setText("")
        self.logo.setPixmap(QPixmap(linkpath + r'\timg.png'))
        self.logo.setObjectName("logo")
        self.text = QLabel(self.groupBox_4)
        self.text.setGeometry(QRect(180, 10, 290, 50))
        palette = QPalette()
        brush = QBrush(QColor(0, 85, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush = QBrush(QColor(0, 85, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(0, 85, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        brush = QBrush(QColor(0, 85, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        brush = QBrush(QColor(0, 85, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush)
        self.text.setPalette(palette)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.text.setFont(font)
        self.text.setAlignment(Qt.AlignCenter)
        self.text.setObjectName("text")
        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setStyleSheet("background-color: rgb(52, 59, 72);\n"
                                      "border-radius:10;\n"
                                      "")
        self.groupBox_5.setGeometry(QRect(590, 240, 180, 180))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.login = QPushButton(self.groupBox_5)
        self.login.setGeometry(QRect(40, 40, 90, 30))
        font = QFont()
        font.setFamily("微软雅黑")
        self.login.setStyleSheet("color: rgb(255, 255, 255);\n")
        self.login.setFont(font)
        self.login.setObjectName("login")
        self.logout = QPushButton(self.groupBox_5)
        self.logout.setGeometry(QRect(60, 100, 60, 30))
        font = QFont()
        font.setFamily("微软雅黑")
        self.logout.setStyleSheet("color: rgb(255, 255, 255);\n")
        self.logout.setFont(font)
        self.logout.setObjectName("logout")
        self.groupBox_6 = QGroupBox(self.centralwidget)
        self.groupBox_6.setStyleSheet("background-color: rgb(52, 59, 72);\n"
                                 "border-radius:10;\n"
                                 "")
        self.groupBox_6.setGeometry(QRect(590, 70, 180, 160))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.linkStyle = QLabel(self.groupBox_6)
        self.linkStyle.setGeometry(QRect(20, 10, 140, 40))
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.linkStyle.setFont(font)
        self.linkStyle.setCursor(QCursor(Qt.ArrowCursor))
        self.linkStyle.setStyleSheet("color: rgb(255, 255, 255);\n")
        self.linkStyle.setToolTip("")
        self.linkStyle.setAlignment(Qt.AlignCenter)
        self.linkStyle.setObjectName("linkStyle")
        self.comboBox = QComboBox(self.groupBox_6)
        self.comboBox.setGeometry(QRect(10, 50,160, 25))
        font = QFont()
        font.setFamily("微软雅黑")
        self.comboBox.setFont(font)
        self.comboBox.setLayoutDirection(Qt.LeftToRight)
        self.comboBox.setStyleSheet("color: rgb(255, 255, 255);\n")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.groupBox_7 = QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QRect(40, 70, 160, 170))
        self.groupBox_7.setStyleSheet("background-color: rgb(52, 59, 72);\n"
                                      "border-radius:10;\n"
                                      "")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.time = QLabel(self.groupBox_7)
        self.time.setGeometry(QRect(10, 10, 90, 40))
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.time.setFont(font)
        self.time.setCursor(QCursor(Qt.ArrowCursor))
        self.time.setStyleSheet("color: rgb(255, 255, 255);\n")
        self.time.setToolTip("")
        self.time.setAlignment(Qt.AlignCenter)
        self.time.setObjectName("time")

        self.timeLable = QLabel(self.groupBox_7)
        self.timeLable.setGeometry(QRect(10, 60, 140, 40))
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.timeLable.setFont(font)
        self.timeLable.setCursor(QCursor(Qt.ArrowCursor))
        self.timeLable.setStyleSheet("color: rgb(255, 255, 255);\n")
        self.timeLable.setToolTip("")
        self.timeLable.setAlignment(Qt.AlignCenter)
        self.timeLable.setObjectName("timeLable")
        timer = QTimer(self)
        timer.timeout.connect(self.showTime)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.user.setText(_translate("MainWindow", "用户名"))
        self.passwd.setText(_translate("MainWindow", "密  码"))
        self.passwdCB.setText(_translate("MainWindow", "记住密码"))
        self.auto_login.setText(_translate("MainWindow", "自动登录"))
        self.status_lable.setText(_translate("MainWindow", "连接状态"))
        self.updateLabel.setText(_translate("MainWindow", "关于 & 更新"))
        self.text.setText(_translate("MainWindow", "上海大学校园网客户端"))
        self.login.setText(_translate("MainWindow", "连接 LogIn"))
        self.logout.setText(_translate("MainWindow", "下线"))
        self.linkStyle.setText(_translate("MainWindow", "连接方式"))
        self.time.setText(_translate("MainWindow", "当前时间"))
        self.comboBox.setItemText(0, _translate("MainWindow", "        请选择"))
        self.comboBox.setItemText(1, _translate("MainWindow", "       有线连接"))
        self.comboBox.setItemText(2, _translate("MainWindow", "       WIFI连接"))
